export const siteConfig = {
  title: "OpenTaint",
  description: "Formal program analysis for security agents. Make every security review protect every future commit.",
  url: "https://opentaint.org",
  author: "Seqra Team",
  twitter: "@seqradev",
  github: "https://github.com/seqra/opentaint",
  discord: "https://discord.gg/6BXDfbP4p9",
} as const;

export const defaultKeywords = [
  "spring sast",
  "java static analysis",
  "kotlin security analyzer",
  "stored injection",
  "semgrep alternative",
  "codeql alternative",
  "cross-endpoint flow",
  "AST-pattern rules",
  "formal program analysis",
  "formal dataflow analysis",
  "AI agent security",
  "security agents",
  "taint analysis engine",
  "open source sast",
  "application security debt",
  "continuous application security",
  "devsecops security scanner",
  "Semgrep Pro alternative",
  "CodeQL alternative",
];
